var hierarchy =
[
    [ "_CPOINT", "struct___c_p_o_i_n_t.html", null ],
    [ "_DIACTIONA", "struct___d_i_a_c_t_i_o_n_a.html", null ],
    [ "_DIACTIONFORMATA", "struct___d_i_a_c_t_i_o_n_f_o_r_m_a_t_a.html", null ],
    [ "_DIACTIONFORMATW", "struct___d_i_a_c_t_i_o_n_f_o_r_m_a_t_w.html", null ],
    [ "_DIACTIONW", "struct___d_i_a_c_t_i_o_n_w.html", null ],
    [ "_DICOLORSET", "struct___d_i_c_o_l_o_r_s_e_t.html", null ],
    [ "_DICONFIGUREDEVICESPARAMSA", "struct___d_i_c_o_n_f_i_g_u_r_e_d_e_v_i_c_e_s_p_a_r_a_m_s_a.html", null ],
    [ "_DICONFIGUREDEVICESPARAMSW", "struct___d_i_c_o_n_f_i_g_u_r_e_d_e_v_i_c_e_s_p_a_r_a_m_s_w.html", null ],
    [ "_DIDATAFORMAT", "struct___d_i_d_a_t_a_f_o_r_m_a_t.html", null ],
    [ "_DIDEVICEIMAGEINFOA", "struct___d_i_d_e_v_i_c_e_i_m_a_g_e_i_n_f_o_a.html", null ],
    [ "_DIDEVICEIMAGEINFOHEADERA", "struct___d_i_d_e_v_i_c_e_i_m_a_g_e_i_n_f_o_h_e_a_d_e_r_a.html", null ],
    [ "_DIDEVICEIMAGEINFOHEADERW", "struct___d_i_d_e_v_i_c_e_i_m_a_g_e_i_n_f_o_h_e_a_d_e_r_w.html", null ],
    [ "_DIDEVICEIMAGEINFOW", "struct___d_i_d_e_v_i_c_e_i_m_a_g_e_i_n_f_o_w.html", null ],
    [ "_DIOBJECTDATAFORMAT", "struct___d_i_o_b_j_e_c_t_d_a_t_a_f_o_r_m_a_t.html", null ],
    [ "_GPU_DEVICE", "struct___g_p_u___d_e_v_i_c_e.html", null ],
    [ "sf::priv::ActivityStates", "structsf_1_1priv_1_1_activity_states.html", null ],
    [ "alloc_chain", "structalloc__chain.html", null ],
    [ "sf::AlResource", "classsf_1_1_al_resource.html", [
      [ "sf::SoundBuffer", "classsf_1_1_sound_buffer.html", null ],
      [ "sf::SoundRecorder", "classsf_1_1_sound_recorder.html", [
        [ "NetworkRecorder", "class_network_recorder.html", null ],
        [ "sf::SoundBufferRecorder", "classsf_1_1_sound_buffer_recorder.html", null ]
      ] ],
      [ "sf::SoundSource", "classsf_1_1_sound_source.html", [
        [ "sf::Sound", "classsf_1_1_sound.html", null ],
        [ "sf::SoundStream", "classsf_1_1_sound_stream.html", [
          [ "NetworkAudioStream", "class_network_audio_stream.html", null ],
          [ "sf::Music", "classsf_1_1_music.html", null ]
        ] ]
      ] ]
    ] ],
    [ "sf::priv::AudioDevice", "classsf_1_1priv_1_1_audio_device.html", null ],
    [ "BDF_PropertyRec_", "struct_b_d_f___property_rec__.html", null ],
    [ "sf::BlendMode", "structsf_1_1_blend_mode.html", null ],
    [ "DOODLE_JUMP::Logic::BonusStrategy", "class_d_o_o_d_l_e___j_u_m_p_1_1_logic_1_1_bonus_strategy.html", [
      [ "DOODLE_JUMP::Logic::JetPackBonus", "class_d_o_o_d_l_e___j_u_m_p_1_1_logic_1_1_jet_pack_bonus.html", null ],
      [ "DOODLE_JUMP::Logic::JumpBonus", "class_d_o_o_d_l_e___j_u_m_p_1_1_logic_1_1_jump_bonus.html", null ]
    ] ],
    [ "DOODLE_JUMP::Logic::Camera", "class_d_o_o_d_l_e___j_u_m_p_1_1_logic_1_1_camera.html", null ],
    [ "sf::SoundStream::Chunk", "structsf_1_1_sound_stream_1_1_chunk.html", null ],
    [ "CID_FaceDictRec_", "struct_c_i_d___face_dict_rec__.html", null ],
    [ "CID_FaceInfoRec_", "struct_c_i_d___face_info_rec__.html", null ],
    [ "sf::priv::SoundFileReaderFlac::ClientData", "structsf_1_1priv_1_1_sound_file_reader_flac_1_1_client_data.html", null ],
    [ "sf::Clipboard", "classsf_1_1_clipboard.html", null ],
    [ "sf::priv::ClipboardImpl", "classsf_1_1priv_1_1_clipboard_impl.html", null ],
    [ "sf::Clock", "classsf_1_1_clock.html", null ],
    [ "sf::priv::ClockImpl", "classsf_1_1priv_1_1_clock_impl.html", null ],
    [ "CocoaAppDelegate()", "category_cocoa_app_delegate_07_08.html", null ],
    [ "sf::Color", "classsf_1_1_color.html", null ],
    [ "sf::ContextSettings", "structsf_1_1_context_settings.html", null ],
    [ "sf::Shader::CurrentTextureType", "structsf_1_1_shader_1_1_current_texture_type.html", null ],
    [ "DICONDITION", "struct_d_i_c_o_n_d_i_t_i_o_n.html", null ],
    [ "DICONSTANTFORCE", "struct_d_i_c_o_n_s_t_a_n_t_f_o_r_c_e.html", null ],
    [ "DICUSTOMFORCE", "struct_d_i_c_u_s_t_o_m_f_o_r_c_e.html", null ],
    [ "DIDEVCAPS", "struct_d_i_d_e_v_c_a_p_s.html", null ],
    [ "DIDEVCAPS_DX3", "struct_d_i_d_e_v_c_a_p_s___d_x3.html", null ],
    [ "DIDEVICEINSTANCE_DX3A", "struct_d_i_d_e_v_i_c_e_i_n_s_t_a_n_c_e___d_x3_a.html", null ],
    [ "DIDEVICEINSTANCE_DX3W", "struct_d_i_d_e_v_i_c_e_i_n_s_t_a_n_c_e___d_x3_w.html", null ],
    [ "DIDEVICEINSTANCEA", "struct_d_i_d_e_v_i_c_e_i_n_s_t_a_n_c_e_a.html", null ],
    [ "DIDEVICEINSTANCEW", "struct_d_i_d_e_v_i_c_e_i_n_s_t_a_n_c_e_w.html", null ],
    [ "DIDEVICEOBJECTDATA", "struct_d_i_d_e_v_i_c_e_o_b_j_e_c_t_d_a_t_a.html", null ],
    [ "DIDEVICEOBJECTDATA_DX3", "struct_d_i_d_e_v_i_c_e_o_b_j_e_c_t_d_a_t_a___d_x3.html", null ],
    [ "DIDEVICEOBJECTINSTANCE_DX3A", "struct_d_i_d_e_v_i_c_e_o_b_j_e_c_t_i_n_s_t_a_n_c_e___d_x3_a.html", null ],
    [ "DIDEVICEOBJECTINSTANCE_DX3W", "struct_d_i_d_e_v_i_c_e_o_b_j_e_c_t_i_n_s_t_a_n_c_e___d_x3_w.html", null ],
    [ "DIDEVICEOBJECTINSTANCEA", "struct_d_i_d_e_v_i_c_e_o_b_j_e_c_t_i_n_s_t_a_n_c_e_a.html", null ],
    [ "DIDEVICEOBJECTINSTANCEW", "struct_d_i_d_e_v_i_c_e_o_b_j_e_c_t_i_n_s_t_a_n_c_e_w.html", null ],
    [ "DIEFFECT", "struct_d_i_e_f_f_e_c_t.html", null ],
    [ "DIEFFECT_DX5", "struct_d_i_e_f_f_e_c_t___d_x5.html", null ],
    [ "DIEFFECTINFOA", "struct_d_i_e_f_f_e_c_t_i_n_f_o_a.html", null ],
    [ "DIEFFECTINFOW", "struct_d_i_e_f_f_e_c_t_i_n_f_o_w.html", null ],
    [ "DIEFFESCAPE", "struct_d_i_e_f_f_e_s_c_a_p_e.html", null ],
    [ "DIENVELOPE", "struct_d_i_e_n_v_e_l_o_p_e.html", null ],
    [ "DIFILEEFFECT", "struct_d_i_f_i_l_e_e_f_f_e_c_t.html", null ],
    [ "DIJOYSTATE", "struct_d_i_j_o_y_s_t_a_t_e.html", null ],
    [ "DIJOYSTATE2", "struct_d_i_j_o_y_s_t_a_t_e2.html", null ],
    [ "DIMOUSESTATE", "struct_d_i_m_o_u_s_e_s_t_a_t_e.html", null ],
    [ "DIMOUSESTATE2", "struct_d_i_m_o_u_s_e_s_t_a_t_e2.html", null ],
    [ "DIPERIODIC", "struct_d_i_p_e_r_i_o_d_i_c.html", null ],
    [ "DIPROPCAL", "struct_d_i_p_r_o_p_c_a_l.html", null ],
    [ "DIPROPCALPOV", "struct_d_i_p_r_o_p_c_a_l_p_o_v.html", null ],
    [ "DIPROPCPOINTS", "struct_d_i_p_r_o_p_c_p_o_i_n_t_s.html", null ],
    [ "DIPROPDWORD", "struct_d_i_p_r_o_p_d_w_o_r_d.html", null ],
    [ "DIPROPGUIDANDPATH", "struct_d_i_p_r_o_p_g_u_i_d_a_n_d_p_a_t_h.html", null ],
    [ "DIPROPHEADER", "struct_d_i_p_r_o_p_h_e_a_d_e_r.html", null ],
    [ "DIPROPPOINTER", "struct_d_i_p_r_o_p_p_o_i_n_t_e_r.html", null ],
    [ "DIPROPRANGE", "struct_d_i_p_r_o_p_r_a_n_g_e.html", null ],
    [ "DIPROPSTRING", "struct_d_i_p_r_o_p_s_t_r_i_n_g.html", null ],
    [ "DIRAMPFORCE", "struct_d_i_r_a_m_p_f_o_r_c_e.html", null ],
    [ "sf::Drawable", "classsf_1_1_drawable.html", [
      [ "DOODLE_JUMP::View::TileMap", "class_d_o_o_d_l_e___j_u_m_p_1_1_view_1_1_tile_map.html", null ],
      [ "Effect", "class_effect.html", [
        [ "Edge", "class_edge.html", null ],
        [ "Geometry", "class_geometry.html", null ],
        [ "Pixelate", "class_pixelate.html", null ],
        [ "StormBlink", "class_storm_blink.html", null ],
        [ "WaveBlur", "class_wave_blur.html", null ]
      ] ],
      [ "sf::Shape", "classsf_1_1_shape.html", [
        [ "sf::CircleShape", "classsf_1_1_circle_shape.html", null ],
        [ "sf::ConvexShape", "classsf_1_1_convex_shape.html", null ],
        [ "sf::RectangleShape", "classsf_1_1_rectangle_shape.html", null ]
      ] ],
      [ "sf::Sprite", "classsf_1_1_sprite.html", null ],
      [ "sf::Text", "classsf_1_1_text.html", null ],
      [ "sf::VertexArray", "classsf_1_1_vertex_array.html", null ],
      [ "sf::VertexBuffer", "classsf_1_1_vertex_buffer.html", null ]
    ] ],
    [ "EFXEAXREVERBPROPERTIES", "struct_e_f_x_e_a_x_r_e_v_e_r_b_p_r_o_p_e_r_t_i_e_s.html", null ],
    [ "std::enable_shared_from_this", null, [
      [ "DOODLE_JUMP::View::PlatformRenderer", "class_d_o_o_d_l_e___j_u_m_p_1_1_view_1_1_platform_renderer.html", null ],
      [ "DOODLE_JUMP::View::PlayerRenderer", "class_d_o_o_d_l_e___j_u_m_p_1_1_view_1_1_player_renderer.html", null ]
    ] ],
    [ "DOODLE_JUMP::Logic::Entity", "class_d_o_o_d_l_e___j_u_m_p_1_1_logic_1_1_entity.html", [
      [ "DOODLE_JUMP::Logic::Bonus", "class_d_o_o_d_l_e___j_u_m_p_1_1_logic_1_1_bonus.html", null ],
      [ "DOODLE_JUMP::Logic::Platform", "class_d_o_o_d_l_e___j_u_m_p_1_1_logic_1_1_platform.html", [
        [ "DOODLE_JUMP::Logic::PlatformHorizontal", "class_d_o_o_d_l_e___j_u_m_p_1_1_logic_1_1_platform_horizontal.html", null ],
        [ "DOODLE_JUMP::Logic::PlatformStatic", "class_d_o_o_d_l_e___j_u_m_p_1_1_logic_1_1_platform_static.html", null ],
        [ "DOODLE_JUMP::Logic::PlatformTemporary", "class_d_o_o_d_l_e___j_u_m_p_1_1_logic_1_1_platform_temporary.html", null ],
        [ "DOODLE_JUMP::Logic::PlatformVertical", "class_d_o_o_d_l_e___j_u_m_p_1_1_logic_1_1_platform_vertical.html", null ]
      ] ],
      [ "DOODLE_JUMP::Logic::Player", "class_d_o_o_d_l_e___j_u_m_p_1_1_logic_1_1_player.html", null ]
    ] ],
    [ "DOODLE_JUMP::Logic::EntityModel", "class_d_o_o_d_l_e___j_u_m_p_1_1_logic_1_1_entity_model.html", [
      [ "DOODLE_JUMP::Logic::BonusCreator", "class_d_o_o_d_l_e___j_u_m_p_1_1_logic_1_1_bonus_creator.html", null ],
      [ "DOODLE_JUMP::Logic::PlatformHorizontalCreator", "class_d_o_o_d_l_e___j_u_m_p_1_1_logic_1_1_platform_horizontal_creator.html", null ],
      [ "DOODLE_JUMP::Logic::PlatformStaticCreator", "class_d_o_o_d_l_e___j_u_m_p_1_1_logic_1_1_platform_static_creator.html", null ],
      [ "DOODLE_JUMP::Logic::PlatformTemporaryCreator", "class_d_o_o_d_l_e___j_u_m_p_1_1_logic_1_1_platform_temporary_creator.html", null ],
      [ "DOODLE_JUMP::Logic::PlatformVerticalCreator", "class_d_o_o_d_l_e___j_u_m_p_1_1_logic_1_1_platform_vertical_creator.html", null ],
      [ "DOODLE_JUMP::Logic::PlayerCreator", "class_d_o_o_d_l_e___j_u_m_p_1_1_logic_1_1_player_creator.html", null ]
    ] ],
    [ "DOODLE_JUMP::View::EntityView", "class_d_o_o_d_l_e___j_u_m_p_1_1_view_1_1_entity_view.html", null ],
    [ "sf::Event", "classsf_1_1_event.html", null ],
    [ "FLAC__EntropyCodingMethod", "struct_f_l_a_c_____entropy_coding_method.html", null ],
    [ "FLAC__EntropyCodingMethod_PartitionedRice", "struct_f_l_a_c_____entropy_coding_method___partitioned_rice.html", null ],
    [ "FLAC__EntropyCodingMethod_PartitionedRiceContents", "struct_f_l_a_c_____entropy_coding_method___partitioned_rice_contents.html", null ],
    [ "FLAC__Frame", "struct_f_l_a_c_____frame.html", null ],
    [ "FLAC__FrameFooter", "struct_f_l_a_c_____frame_footer.html", null ],
    [ "FLAC__FrameHeader", "struct_f_l_a_c_____frame_header.html", null ],
    [ "FLAC__IOCallbacks", "struct_f_l_a_c_____i_o_callbacks.html", null ],
    [ "FLAC__StreamDecoder", "struct_f_l_a_c_____stream_decoder.html", null ],
    [ "FLAC__StreamEncoder", "struct_f_l_a_c_____stream_encoder.html", null ],
    [ "FLAC__StreamMetadata", "struct_f_l_a_c_____stream_metadata.html", null ],
    [ "FLAC__StreamMetadata_Application", "struct_f_l_a_c_____stream_metadata___application.html", null ],
    [ "FLAC__StreamMetadata_CueSheet", "struct_f_l_a_c_____stream_metadata___cue_sheet.html", null ],
    [ "FLAC__StreamMetadata_CueSheet_Index", "struct_f_l_a_c_____stream_metadata___cue_sheet___index.html", null ],
    [ "FLAC__StreamMetadata_CueSheet_Track", "struct_f_l_a_c_____stream_metadata___cue_sheet___track.html", null ],
    [ "FLAC__StreamMetadata_Padding", "struct_f_l_a_c_____stream_metadata___padding.html", null ],
    [ "FLAC__StreamMetadata_Picture", "struct_f_l_a_c_____stream_metadata___picture.html", null ],
    [ "FLAC__StreamMetadata_SeekPoint", "struct_f_l_a_c_____stream_metadata___seek_point.html", null ],
    [ "FLAC__StreamMetadata_SeekTable", "struct_f_l_a_c_____stream_metadata___seek_table.html", null ],
    [ "FLAC__StreamMetadata_StreamInfo", "struct_f_l_a_c_____stream_metadata___stream_info.html", null ],
    [ "FLAC__StreamMetadata_Unknown", "struct_f_l_a_c_____stream_metadata___unknown.html", null ],
    [ "FLAC__StreamMetadata_VorbisComment", "struct_f_l_a_c_____stream_metadata___vorbis_comment.html", null ],
    [ "FLAC__StreamMetadata_VorbisComment_Entry", "struct_f_l_a_c_____stream_metadata___vorbis_comment___entry.html", null ],
    [ "FLAC__Subframe", "struct_f_l_a_c_____subframe.html", null ],
    [ "FLAC__Subframe_Constant", "struct_f_l_a_c_____subframe___constant.html", null ],
    [ "FLAC__Subframe_Fixed", "struct_f_l_a_c_____subframe___fixed.html", null ],
    [ "FLAC__Subframe_LPC", "struct_f_l_a_c_____subframe___l_p_c.html", null ],
    [ "FLAC__Subframe_Verbatim", "struct_f_l_a_c_____subframe___verbatim.html", null ],
    [ "sf::Font", "classsf_1_1_font.html", null ],
    [ "FT_BBox_", "struct_f_t___b_box__.html", null ],
    [ "FT_Bitmap_", "struct_f_t___bitmap__.html", null ],
    [ "FT_Bitmap_Size_", "struct_f_t___bitmap___size__.html", null ],
    [ "FT_BitmapGlyphRec_", "struct_f_t___bitmap_glyph_rec__.html", null ],
    [ "FT_CharMapRec_", "struct_f_t___char_map_rec__.html", null ],
    [ "FT_Data_", "struct_f_t___data__.html", null ],
    [ "FT_FaceRec_", "struct_f_t___face_rec__.html", null ],
    [ "FT_Generic_", "struct_f_t___generic__.html", null ],
    [ "FT_Glyph_Class_", "struct_f_t___glyph___class__.html", null ],
    [ "FT_Glyph_Metrics_", "struct_f_t___glyph___metrics__.html", null ],
    [ "FT_GlyphRec_", "struct_f_t___glyph_rec__.html", null ],
    [ "FT_GlyphSlotRec_", "struct_f_t___glyph_slot_rec__.html", null ],
    [ "FT_Incremental_FuncsRec_", "struct_f_t___incremental___funcs_rec__.html", null ],
    [ "FT_Incremental_InterfaceRec_", "struct_f_t___incremental___interface_rec__.html", null ],
    [ "FT_Incremental_MetricsRec_", "struct_f_t___incremental___metrics_rec__.html", null ],
    [ "FT_ListNodeRec_", "struct_f_t___list_node_rec__.html", null ],
    [ "FT_ListRec_", "struct_f_t___list_rec__.html", null ],
    [ "FT_Matrix_", "struct_f_t___matrix__.html", null ],
    [ "FT_MemoryRec_", "struct_f_t___memory_rec__.html", null ],
    [ "FT_MM_Axis_", "struct_f_t___m_m___axis__.html", null ],
    [ "FT_MM_Var_", "struct_f_t___m_m___var__.html", null ],
    [ "FT_Module_Class_", "struct_f_t___module___class__.html", null ],
    [ "FT_Multi_Master_", "struct_f_t___multi___master__.html", null ],
    [ "FT_Open_Args_", "struct_f_t___open___args__.html", null ],
    [ "FT_Outline_", "struct_f_t___outline__.html", null ],
    [ "FT_Outline_Funcs_", "struct_f_t___outline___funcs__.html", null ],
    [ "FT_OutlineGlyphRec_", "struct_f_t___outline_glyph_rec__.html", null ],
    [ "FT_Parameter_", "struct_f_t___parameter__.html", null ],
    [ "FT_Prop_GlyphToScriptMap_", "struct_f_t___prop___glyph_to_script_map__.html", null ],
    [ "FT_Prop_IncreaseXHeight_", "struct_f_t___prop___increase_x_height__.html", null ],
    [ "FT_Raster_Funcs_", "struct_f_t___raster___funcs__.html", null ],
    [ "FT_Raster_Params_", "struct_f_t___raster___params__.html", null ],
    [ "FT_Renderer_Class_", "struct_f_t___renderer___class__.html", null ],
    [ "FT_SfntName_", "struct_f_t___sfnt_name__.html", null ],
    [ "FT_Size_Metrics_", "struct_f_t___size___metrics__.html", null ],
    [ "FT_Size_RequestRec_", "struct_f_t___size___request_rec__.html", null ],
    [ "FT_SizeRec_", "struct_f_t___size_rec__.html", null ],
    [ "FT_Span_", "struct_f_t___span__.html", null ],
    [ "FT_StreamDesc_", "union_f_t___stream_desc__.html", null ],
    [ "FT_StreamRec_", "struct_f_t___stream_rec__.html", null ],
    [ "FT_UnitVector_", "struct_f_t___unit_vector__.html", null ],
    [ "FT_Var_Axis_", "struct_f_t___var___axis__.html", null ],
    [ "FT_Var_Named_Style_", "struct_f_t___var___named___style__.html", null ],
    [ "FT_Vector_", "struct_f_t___vector__.html", null ],
    [ "FT_WinFNT_HeaderRec_", "struct_f_t___win_f_n_t___header_rec__.html", null ],
    [ "FTC_ImageTypeRec_", "struct_f_t_c___image_type_rec__.html", null ],
    [ "FTC_SBitRec_", "struct_f_t_c___s_bit_rec__.html", null ],
    [ "FTC_ScalerRec_", "struct_f_t_c___scaler_rec__.html", null ],
    [ "DOODLE_JUMP::View::Game", "class_d_o_o_d_l_e___j_u_m_p_1_1_view_1_1_game.html", null ],
    [ "sf::GlResource", "classsf_1_1_gl_resource.html", [
      [ "sf::Context", "classsf_1_1_context.html", null ],
      [ "sf::Shader", "classsf_1_1_shader.html", null ],
      [ "sf::Texture", "classsf_1_1_texture.html", null ],
      [ "sf::VertexBuffer", "classsf_1_1_vertex_buffer.html", null ],
      [ "sf::Window", "classsf_1_1_window.html", [
        [ "sf::RenderWindow", "classsf_1_1_render_window.html", null ]
      ] ],
      [ "sf::priv::RenderTextureImplDefault", "classsf_1_1priv_1_1_render_texture_impl_default.html", null ],
      [ "sf::priv::RenderTextureImplFBO", "classsf_1_1priv_1_1_render_texture_impl_f_b_o.html", null ]
    ] ],
    [ "GLXHyperpipeConfigSGIX", "struct_g_l_x_hyperpipe_config_s_g_i_x.html", null ],
    [ "GLXHyperpipeNetworkSGIX", "struct_g_l_x_hyperpipe_network_s_g_i_x.html", null ],
    [ "GLXPipeRect", "struct_g_l_x_pipe_rect.html", null ],
    [ "GLXPipeRectLimits", "struct_g_l_x_pipe_rect_limits.html", null ],
    [ "sf::Glyph", "classsf_1_1_glyph.html", null ],
    [ "sf::Joystick::Identification", "structsf_1_1_joystick_1_1_identification.html", null ],
    [ "sf::Image", "classsf_1_1_image.html", null ],
    [ "sf::Font::Info", "structsf_1_1_font_1_1_info.html", null ],
    [ "sf::SoundFileReader::Info", "structsf_1_1_sound_file_reader_1_1_info.html", null ],
    [ "sf::priv::InputImpl", "classsf_1_1priv_1_1_input_impl.html", null ],
    [ "sf::InputStream", "classsf_1_1_input_stream.html", [
      [ "sf::FileInputStream", "classsf_1_1_file_input_stream.html", null ],
      [ "sf::MemoryInputStream", "classsf_1_1_memory_input_stream.html", null ],
      [ "sf::priv::ResourceStream", "classsf_1_1priv_1_1_resource_stream.html", null ]
    ] ],
    [ "sf::IpAddress", "classsf_1_1_ip_address.html", null ],
    [ "sf::Joystick", "classsf_1_1_joystick.html", null ],
    [ "sf::Event::JoystickButtonEvent", "structsf_1_1_event_1_1_joystick_button_event.html", null ],
    [ "sf::priv::JoystickCaps", "structsf_1_1priv_1_1_joystick_caps.html", null ],
    [ "sf::Event::JoystickConnectEvent", "structsf_1_1_event_1_1_joystick_connect_event.html", null ],
    [ "sf::priv::JoystickImpl", "classsf_1_1priv_1_1_joystick_impl.html", null ],
    [ "sf::Event::JoystickMoveEvent", "structsf_1_1_event_1_1_joystick_move_event.html", null ],
    [ "sf::priv::JoystickState", "structsf_1_1priv_1_1_joystick_state.html", null ],
    [ "sf::Keyboard", "classsf_1_1_keyboard.html", null ],
    [ "sf::Event::KeyEvent", "structsf_1_1_event_1_1_key_event.html", null ],
    [ "sf::Listener", "classsf_1_1_listener.html", null ],
    [ "Matrix< Columns, Rows >", "struct_matrix.html", null ],
    [ "sf::priv::Matrix< Columns, Rows >", "structsf_1_1priv_1_1_matrix.html", null ],
    [ "ModifiersState", "struct_modifiers_state.html", null ],
    [ "sf::Mouse", "classsf_1_1_mouse.html", null ],
    [ "sf::Event::MouseButtonEvent", "structsf_1_1_event_1_1_mouse_button_event.html", null ],
    [ "sf::Event::MouseMoveEvent", "structsf_1_1_event_1_1_mouse_move_event.html", null ],
    [ "sf::Event::MouseWheelEvent", "structsf_1_1_event_1_1_mouse_wheel_event.html", null ],
    [ "sf::Event::MouseWheelScrollEvent", "structsf_1_1_event_1_1_mouse_wheel_scroll_event.html", null ],
    [ "sf::NonCopyable", "classsf_1_1_non_copyable.html", [
      [ "sf::Context", "classsf_1_1_context.html", null ],
      [ "sf::Cursor", "classsf_1_1_cursor.html", null ],
      [ "sf::FileInputStream", "classsf_1_1_file_input_stream.html", null ],
      [ "sf::Ftp", "classsf_1_1_ftp.html", null ],
      [ "sf::Ftp::DataChannel", "classsf_1_1_ftp_1_1_data_channel.html", null ],
      [ "sf::GlResource::TransientContextLock", "classsf_1_1_gl_resource_1_1_transient_context_lock.html", null ],
      [ "sf::Http", "classsf_1_1_http.html", null ],
      [ "sf::InputSoundFile", "classsf_1_1_input_sound_file.html", null ],
      [ "sf::Lock", "classsf_1_1_lock.html", null ],
      [ "sf::Mutex", "classsf_1_1_mutex.html", null ],
      [ "sf::OutputSoundFile", "classsf_1_1_output_sound_file.html", null ],
      [ "sf::RenderTarget", "classsf_1_1_render_target.html", [
        [ "sf::RenderTexture", "classsf_1_1_render_texture.html", null ],
        [ "sf::RenderWindow", "classsf_1_1_render_window.html", null ]
      ] ],
      [ "sf::Shader", "classsf_1_1_shader.html", null ],
      [ "sf::Shader::UniformBinder", "structsf_1_1_shader_1_1_uniform_binder.html", null ],
      [ "sf::Socket", "classsf_1_1_socket.html", [
        [ "sf::TcpListener", "classsf_1_1_tcp_listener.html", null ],
        [ "sf::TcpSocket", "classsf_1_1_tcp_socket.html", null ],
        [ "sf::UdpSocket", "classsf_1_1_udp_socket.html", null ]
      ] ],
      [ "sf::Thread", "classsf_1_1_thread.html", null ],
      [ "sf::ThreadLocal", "classsf_1_1_thread_local.html", [
        [ "sf::ThreadLocalPtr< T >", "classsf_1_1_thread_local_ptr.html", null ]
      ] ],
      [ "sf::Window", "classsf_1_1_window.html", null ],
      [ "sf::priv::CursorImpl", "classsf_1_1priv_1_1_cursor_impl.html", null ],
      [ "sf::priv::CursorImpl", "classsf_1_1priv_1_1_cursor_impl.html", null ],
      [ "sf::priv::CursorImpl", "classsf_1_1priv_1_1_cursor_impl.html", null ],
      [ "sf::priv::CursorImpl", "classsf_1_1priv_1_1_cursor_impl.html", null ],
      [ "sf::priv::CursorImpl", "classsf_1_1priv_1_1_cursor_impl.html", null ],
      [ "sf::priv::GlContext", "classsf_1_1priv_1_1_gl_context.html", [
        [ "sf::priv::EaglContext", "classsf_1_1priv_1_1_eagl_context.html", null ],
        [ "sf::priv::EglContext", "classsf_1_1priv_1_1_egl_context.html", null ],
        [ "sf::priv::GlxContext", "classsf_1_1priv_1_1_glx_context.html", null ],
        [ "sf::priv::SFContext", "classsf_1_1priv_1_1_s_f_context.html", null ],
        [ "sf::priv::WglContext", "classsf_1_1priv_1_1_wgl_context.html", null ]
      ] ],
      [ "sf::priv::HIDInputManager", "classsf_1_1priv_1_1_h_i_d_input_manager.html", null ],
      [ "sf::priv::HIDJoystickManager", "classsf_1_1priv_1_1_h_i_d_joystick_manager.html", null ],
      [ "sf::priv::ImageLoader", "classsf_1_1priv_1_1_image_loader.html", null ],
      [ "sf::priv::JoystickManager", "classsf_1_1priv_1_1_joystick_manager.html", null ],
      [ "sf::priv::MutexImpl", "classsf_1_1priv_1_1_mutex_impl.html", null ],
      [ "sf::priv::MutexImpl", "classsf_1_1priv_1_1_mutex_impl.html", null ],
      [ "sf::priv::RenderTextureImpl", "classsf_1_1priv_1_1_render_texture_impl.html", [
        [ "sf::priv::RenderTextureImplDefault", "classsf_1_1priv_1_1_render_texture_impl_default.html", null ],
        [ "sf::priv::RenderTextureImplFBO", "classsf_1_1priv_1_1_render_texture_impl_f_b_o.html", null ]
      ] ],
      [ "sf::priv::SensorManager", "classsf_1_1priv_1_1_sensor_manager.html", null ],
      [ "sf::priv::ThreadImpl", "classsf_1_1priv_1_1_thread_impl.html", null ],
      [ "sf::priv::ThreadImpl", "classsf_1_1priv_1_1_thread_impl.html", null ],
      [ "sf::priv::ThreadLocalImpl", "classsf_1_1priv_1_1_thread_local_impl.html", null ],
      [ "sf::priv::ThreadLocalImpl", "classsf_1_1priv_1_1_thread_local_impl.html", null ],
      [ "sf::priv::WindowImpl", "classsf_1_1priv_1_1_window_impl.html", [
        [ "sf::priv::WindowImplAndroid", "classsf_1_1priv_1_1_window_impl_android.html", null ],
        [ "sf::priv::WindowImplCocoa", "classsf_1_1priv_1_1_window_impl_cocoa.html", null ],
        [ "sf::priv::WindowImplUIKit", "classsf_1_1priv_1_1_window_impl_u_i_kit.html", null ],
        [ "sf::priv::WindowImplWin32", "classsf_1_1priv_1_1_window_impl_win32.html", null ],
        [ "sf::priv::WindowImplX11", "classsf_1_1priv_1_1_window_impl_x11.html", null ]
      ] ]
    ] ],
    [ "NSApplication", null, [
      [ "SFApplication", "interface_s_f_application.html", null ]
    ] ],
    [ "<NSApplicationDelegate>", null, [
      [ "CocoaAppDelegate", "interface_cocoa_app_delegate.html", null ],
      [ "SFApplicationDelegate", "interface_s_f_application_delegate.html", null ]
    ] ],
    [ "NSImage(raw)", "category_n_s_image_07raw_08.html", null ],
    [ "NSObject", null, [
      [ "CocoaAppDelegate", "interface_cocoa_app_delegate.html", null ],
      [ "SFAppDelegate", "interface_s_f_app_delegate.html", null ],
      [ "SFApplicationDelegate", "interface_s_f_application_delegate.html", null ],
      [ "SFViewController", "interface_s_f_view_controller.html", null ]
    ] ],
    [ "NSOpenGLView", null, [
      [ "SFOpenGLView", "interface_s_f_open_g_l_view.html", null ]
    ] ],
    [ "NSResponder", null, [
      [ "SFSilentResponder", "interface_s_f_silent_responder.html", null ],
      [ "SFWindowController", "interface_s_f_window_controller.html", null ]
    ] ],
    [ "NSString(NSString_stdstring)", "category_n_s_string_07_n_s_string__stdstring_08.html", null ],
    [ "NSView", null, [
      [ "SFBlackView", "interface_s_f_black_view.html", null ]
    ] ],
    [ "NSWindow", null, [
      [ "SFWindow", "interface_s_f_window.html", null ],
      [ "SilentWindow", "interface_silent_window.html", null ]
    ] ],
    [ "NSWindow(SFML)", "category_n_s_window_07_s_f_m_l_08.html", null ],
    [ "<NSWindowDelegate>", null, [
      [ "SFWindowController", "interface_s_f_window_controller.html", null ]
    ] ],
    [ "DOODLE_JUMP::Logic::Observer", "class_d_o_o_d_l_e___j_u_m_p_1_1_logic_1_1_observer.html", [
      [ "DOODLE_JUMP::Logic::Score", "class_d_o_o_d_l_e___j_u_m_p_1_1_logic_1_1_score.html", null ],
      [ "DOODLE_JUMP::View::PlatformRenderer", "class_d_o_o_d_l_e___j_u_m_p_1_1_view_1_1_platform_renderer.html", null ],
      [ "DOODLE_JUMP::View::PlayerRenderer", "class_d_o_o_d_l_e___j_u_m_p_1_1_view_1_1_player_renderer.html", null ]
    ] ],
    [ "ogg_iovec_t", "structogg__iovec__t.html", null ],
    [ "ogg_packet", "structogg__packet.html", null ],
    [ "ogg_page", "structogg__page.html", null ],
    [ "ogg_stream_state", "structogg__stream__state.html", null ],
    [ "ogg_sync_state", "structogg__sync__state.html", null ],
    [ "oggpack_buffer", "structoggpack__buffer.html", null ],
    [ "OggVorbis_File", "struct_ogg_vorbis___file.html", null ],
    [ "ov_callbacks", "structov__callbacks.html", null ],
    [ "ovectl_ratemanage2_arg", "structovectl__ratemanage2__arg.html", null ],
    [ "ovectl_ratemanage_arg", "structovectl__ratemanage__arg.html", null ],
    [ "sf::Packet", "classsf_1_1_packet.html", null ],
    [ "PS_BlendRec_", "struct_p_s___blend_rec__.html", null ],
    [ "PS_DesignMap_", "struct_p_s___design_map__.html", null ],
    [ "PS_FontInfoRec_", "struct_p_s___font_info_rec__.html", null ],
    [ "PS_PrivateRec_", "struct_p_s___private_rec__.html", null ],
    [ "DOODLE_JUMP::Logic::Random", "class_d_o_o_d_l_e___j_u_m_p_1_1_logic_1_1_random.html", null ],
    [ "sf::Rect< T >", "classsf_1_1_rect.html", null ],
    [ "sf::Rect< float >", "classsf_1_1_rect.html", null ],
    [ "sf::Rect< int >", "classsf_1_1_rect.html", null ],
    [ "sf::RenderStates", "classsf_1_1_render_states.html", null ],
    [ "sf::Http::Request", "classsf_1_1_http_1_1_request.html", null ],
    [ "sf::Ftp::Response", "classsf_1_1_ftp_1_1_response.html", [
      [ "sf::Ftp::DirectoryResponse", "classsf_1_1_ftp_1_1_directory_response.html", null ],
      [ "sf::Ftp::ListingResponse", "classsf_1_1_ftp_1_1_listing_response.html", null ]
    ] ],
    [ "sf::Http::Response", "classsf_1_1_http_1_1_response.html", null ],
    [ "sf::Sensor", "classsf_1_1_sensor.html", null ],
    [ "sf::Event::SensorEvent", "structsf_1_1_event_1_1_sensor_event.html", null ],
    [ "sf::priv::SensorImpl", "classsf_1_1priv_1_1_sensor_impl.html", null ],
    [ "SFAppDelegate()", "category_s_f_app_delegate_07_08.html", null ],
    [ "sfglx_StrToExtMap_s", "structsfglx___str_to_ext_map__s.html", null ],
    [ "SFMLmainWindow", "struct_s_f_m_lmain_window.html", null ],
    [ "sfogl_StrToExtMap_s", "structsfogl___str_to_ext_map__s.html", null ],
    [ "SFOpenGLView()", "category_s_f_open_g_l_view_07_08.html", null ],
    [ "SFOpenGLView(keyboard)", "category_s_f_open_g_l_view_07keyboard_08.html", null ],
    [ "SFOpenGLView(keyboard_priv)", "category_s_f_open_g_l_view_07keyboard__priv_08.html", null ],
    [ "SFOpenGLView(mouse)", "category_s_f_open_g_l_view_07mouse_08.html", null ],
    [ "SFOpenGLView(mouse_priv)", "category_s_f_open_g_l_view_07mouse__priv_08.html", null ],
    [ "SFView()", "category_s_f_view_07_08.html", null ],
    [ "sfwgl_StrToExtMap_s", "structsfwgl___str_to_ext_map__s.html", null ],
    [ "SFWindowController()", "category_s_f_window_controller_07_08.html", null ],
    [ "sf::Event::SizeEvent", "structsf_1_1_event_1_1_size_event.html", null ],
    [ "sf::priv::SocketImpl", "classsf_1_1priv_1_1_socket_impl.html", null ],
    [ "sf::priv::SocketInitializer", "structsf_1_1priv_1_1_socket_initializer.html", null ],
    [ "sf::SocketSelector", "classsf_1_1_socket_selector.html", null ],
    [ "sf::SocketSelector::SocketSelectorImpl", "structsf_1_1_socket_selector_1_1_socket_selector_impl.html", null ],
    [ "sf::SoundFileFactory", "classsf_1_1_sound_file_factory.html", null ],
    [ "sf::SoundFileReader", "classsf_1_1_sound_file_reader.html", [
      [ "sf::priv::SoundFileReaderFlac", "classsf_1_1priv_1_1_sound_file_reader_flac.html", null ],
      [ "sf::priv::SoundFileReaderOgg", "classsf_1_1priv_1_1_sound_file_reader_ogg.html", null ],
      [ "sf::priv::SoundFileReaderWav", "classsf_1_1priv_1_1_sound_file_reader_wav.html", null ]
    ] ],
    [ "sf::SoundFileWriter", "classsf_1_1_sound_file_writer.html", [
      [ "sf::priv::SoundFileWriterFlac", "classsf_1_1priv_1_1_sound_file_writer_flac.html", null ],
      [ "sf::priv::SoundFileWriterOgg", "classsf_1_1priv_1_1_sound_file_writer_ogg.html", null ],
      [ "sf::priv::SoundFileWriterWav", "classsf_1_1priv_1_1_sound_file_writer_wav.html", null ]
    ] ],
    [ "sf::Music::Span< T >", "structsf_1_1_music_1_1_span.html", null ],
    [ "sf::Music::Span< Uint64 >", "structsf_1_1_music_1_1_span.html", null ],
    [ "stbi_io_callbacks", "structstbi__io__callbacks.html", null ],
    [ "DOODLE_JUMP::Logic::Stopwatch", "class_d_o_o_d_l_e___j_u_m_p_1_1_logic_1_1_stopwatch.html", null ],
    [ "std::streambuf", null, [
      [ "LogcatStream", "class_logcat_stream.html", null ]
    ] ],
    [ "sf::String", "classsf_1_1_string.html", null ],
    [ "DOODLE_JUMP::Logic::Subject", "class_d_o_o_d_l_e___j_u_m_p_1_1_logic_1_1_subject.html", [
      [ "DOODLE_JUMP::Logic::World", "class_d_o_o_d_l_e___j_u_m_p_1_1_logic_1_1_world.html", null ]
    ] ],
    [ "sf::Event::TextEvent", "structsf_1_1_event_1_1_text_event.html", null ],
    [ "sf::priv::TextureSaver", "classsf_1_1priv_1_1_texture_saver.html", null ],
    [ "priv::ThreadFunc", "structpriv_1_1_thread_func.html", [
      [ "priv::ThreadFunctor< T >", "structpriv_1_1_thread_functor.html", null ],
      [ "priv::ThreadFunctorWithArg< F, A >", "structpriv_1_1_thread_functor_with_arg.html", null ],
      [ "priv::ThreadMemberFunc< C >", "structpriv_1_1_thread_member_func.html", null ]
    ] ],
    [ "sf::Time", "classsf_1_1_time.html", null ],
    [ "sf::Touch", "classsf_1_1_touch.html", null ],
    [ "sf::Event::TouchEvent", "structsf_1_1_event_1_1_touch_event.html", null ],
    [ "sf::Transform", "classsf_1_1_transform.html", null ],
    [ "sf::Transformable", "classsf_1_1_transformable.html", [
      [ "DOODLE_JUMP::View::TileMap", "class_d_o_o_d_l_e___j_u_m_p_1_1_view_1_1_tile_map.html", null ],
      [ "sf::Shape", "classsf_1_1_shape.html", null ],
      [ "sf::Sprite", "classsf_1_1_sprite.html", null ],
      [ "sf::Text", "classsf_1_1_text.html", null ]
    ] ],
    [ "TT_Header_", "struct_t_t___header__.html", null ],
    [ "TT_HoriHeader_", "struct_t_t___hori_header__.html", null ],
    [ "TT_MaxProfile_", "struct_t_t___max_profile__.html", null ],
    [ "TT_OS2_", "struct_t_t___o_s2__.html", null ],
    [ "TT_PCLT_", "struct_t_t___p_c_l_t__.html", null ],
    [ "TT_Postscript_", "struct_t_t___postscript__.html", null ],
    [ "TT_VertHeader_", "struct_t_t___vert_header__.html", null ],
    [ "<UIApplicationDelegate>", null, [
      [ "SFAppDelegate", "interface_s_f_app_delegate.html", null ]
    ] ],
    [ "<UIKeyInput>", null, [
      [ "SFView", "interface_s_f_view.html", null ]
    ] ],
    [ "UIView", null, [
      [ "SFView", "interface_s_f_view.html", null ]
    ] ],
    [ "UIViewController", null, [
      [ "SFViewController", "interface_s_f_view_controller.html", null ]
    ] ],
    [ "sf::Utf< N >", "classsf_1_1_utf.html", null ],
    [ "sf::Utf< 16 >", "classsf_1_1_utf_3_0116_01_4.html", null ],
    [ "sf::Utf< 32 >", "classsf_1_1_utf_3_0132_01_4.html", null ],
    [ "sf::Utf< 8 >", "classsf_1_1_utf_3_018_01_4.html", null ],
    [ "sf::Vector2< T >", "classsf_1_1_vector2.html", null ],
    [ "sf::Vector2< float >", "classsf_1_1_vector2.html", null ],
    [ "sf::Vector2< int >", "classsf_1_1_vector2.html", null ],
    [ "sf::Vector2< unsigned int >", "classsf_1_1_vector2.html", null ],
    [ "sf::Vector3< T >", "classsf_1_1_vector3.html", null ],
    [ "sf::Vector3< float >", "classsf_1_1_vector3.html", null ],
    [ "sf::priv::Vector4< T >", "structsf_1_1priv_1_1_vector4.html", null ],
    [ "Vector4< T >", "struct_vector4.html", null ],
    [ "sf::Vertex", "classsf_1_1_vertex.html", null ],
    [ "sf::VideoMode", "classsf_1_1_video_mode.html", null ],
    [ "sf::priv::VideoModeImpl", "classsf_1_1priv_1_1_video_mode_impl.html", null ],
    [ "sf::View", "classsf_1_1_view.html", null ],
    [ "vorbis_block", "structvorbis__block.html", null ],
    [ "vorbis_comment", "structvorbis__comment.html", null ],
    [ "vorbis_dsp_state", "structvorbis__dsp__state.html", null ],
    [ "vorbis_info", "structvorbis__info.html", null ],
    [ "<WindowImplDelegateProtocol>", "protocol_window_impl_delegate_protocol-p.html", [
      [ "SFViewController", "interface_s_f_view_controller.html", null ],
      [ "SFWindowController", "interface_s_f_window_controller.html", null ]
    ] ]
];